### ISSUE TITLE
Google Drive blocks mass downloading for trans_render

### ISSUE THREAD

**Issue by tanjasper** [NVlabs/FLAT#10]
Thank you for this dataset! When running `python init.py -c trans_render`, the first ~20 pickle files download fine, but then all subsequent files downloaded are just Google Drive's html page saying "We're sorry... but your computer or network may be sending automated queries. To protect our users, we can't process your requests right now." It seems that Google Drive blocks mass downloading. 

Is there a workaround for this? Perhaps a Google Drive link to the entire trans_render folder that we can download or maybe the multiple pickle files can be zipped into a few large zip files? That would be greatly appreciated, thank you!

**Comment by guoqi1123** [comment]
Hi! Thanks for letting us know about this issue. Please send me an email: qguo@seas.harvard.edu and I will reply to you the link to the dataset!
