### ISSUE TITLE
The question of dataset download

### ISSUE THREAD

**Issue by rabunnhinn** [NVlabs/FLAT#14]
Hello,

When I try the init.py file, the files downloaded by googledrivedownloader are all not correct with only 404 information inside.
I try to use gdown but still can not get the file.
I check the issues and found that the google drive link mentioned in #11 is no longer valid.

I am not sure if the problem occurs due to my operation or if the google drive id in init.py is not usable now.
But I would appreciate it if you could help download the dataset.

Thanks and best regards.

**Comment by guoqi1123** [comment]
I apologize for the inconvenience. Please use this link: https://drive.google.com/drive/folders/0B8NQpkbqgQ0SfkZDUEpyZkp5R0FWdkd2Y01XUHBZRXdZamphcHNjWU13bGdFc2IzY0puMU0?resourcekey=0-eXa3YASdYyRJ4gym_JTzpQ&usp=sharing
