### ISSUE TITLE
Dataset not downloading properly

### ISSUE THREAD

**Issue by VC86** [NVlabs/FLAT#2]
On Windows 10, Anaconda 3 I am currently experiencing the following issue:

```
Downloading 1EJqr4pvoCE6VahNcoQB9HFccjMMzzc9a into ./kinect/list/motion_real.txt... Done.
Unzipping...C:\Users\<myusername>\AppData\Roaming\Python\Python36\site-packages\google_drive_downloader\google_drive_downloader.py:78: UserWarning: Ignoring `unzip` since "1EJqr4pvoCE6VahNcoQB9HFccjMMzzc9a" does not look like a valid zip file
  warnings.warn('Ignoring `unzip` since "{}" does not look like a valid zip file'.format(file_id))
Downloading 1XXhu7F8Whz_vxOEk4HUAzlIeMQ8E-XzM into ./kinect/list/motion_real/1519695965359234.png... Done.
Unzipping...C:\Users\<myusername>\AppData\Roaming\Python\Python36\site-packages\google_drive_downloader\google_drive_downloader.py:78: UserWarning: Ignoring `unzip` since "1XXhu7F8Whz_vxOEk4HUAzlIeMQ8E-XzM" does not look like a valid zip file
  warnings.warn('Ignoring `unzip` since "{}" does not look like a valid zip file'.format(file_id))
```
The list goes on for all attempted downloads & unzips. This happens also when running with administrator rights. I've tried debugging in Pycharm and the result is as follows.
```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "C:\Users\<myusername>\.conda\envs\tf190\lib\zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "C:\Users\<myusername>\.conda\envs\tf190\lib\zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```
I've checked that the files cannot be opened even when assigning the .zip extension, with external software. Is there any reason why the script wouldn't run on a Windows platform?

**Comment by guoqi1123** [comment]
Hi, the unzipping warning is normal because not all files in the FLAT dataset are zip files. Can you see the files downloaded inside your FLAT folders? I tried to run the script using a windows 10 machine, and currently did not see problems in downloading files.

**Comment by VC86** [comment]
Hello, indeed, I can see the full tree structure being generated. I thought the warning was indicating a potential failure, i.e., that one would call unzip only for actual readable zip files.

**Comment by guoqi1123** [comment]
You are right. If there is no missing file. This issue will be closed.
