### ISSUE TITLE
can't download the raw measurement of phasor and deeptof

### ISSUE THREAD

**Issue by gtdong-ustc** [NVlabs/FLAT#3]
Through run **python init.py -n all**, I can only download the raw measurement of Kinect. So I ran **python init.py -c phasor** and **python init.py -c deeptof** next to verify that I could download Phasor and DeepToF, but nothing happened. So I want to make sure that you have provided the raw measurement of Phasor and DeepToF data that can download.

**Comment by guoqi1123** [comment]
Thanks for finding this problem! It is already solved, you can pull the repo again and it should work now.
