### ISSUE TITLE
Could not understand the meaning of the label of the test result diagram you gave

### ISSUE THREAD

**Issue by gtdong-ustc** [NVlabs/FLAT#4]
![1519079415682138](https://user-images.githubusercontent.com/26164983/64613253-4bea8b80-d408-11e9-8bc7-db3142270b66.png)
As shown in an example you gave in **FLAT\kinect\list\test**. According to my understanding, the images with labels that **full, ideal, noise, reflection** are depth map. The overall color difference between image with label **noise**  and image with label **reflection** is due to the different scales.  An image with label **Base err** is the difference between labeled depth map  and depth groundtruth.
But by reading your released source code, I realize that ideal is the true raw measurement with 9 channels. So I want to ask the meaning of the four labels that **full, ideal, noise, reflection**. Thanks very much!

**Comment by guoqi1123** [comment]
I think you are basically right.  The 'full' means depth recovered using raw measurements that contain shot noise and multi-path interference; the 'ideal' means depth recovered using raw measurements without shot noise or multi-path interference; the 'noise' means depth recovered using raw measurements with shot-noise only; and the 'reflection' means depth recovered using raw measurements with multi-path interference only.
