### ISSUE TITLE
issues about trans_render data download.

### ISSUE THREAD

**Issue by Hongdou68** [NVlabs/FLAT#7]
Hi, because I want to generate the data using my camera settings, so i need to download the trans_render, but when i doload the trans_render file using 'python init.py -c trans_render', i found there are too much file whose size only 2Kb, there must be some questions, but i didnot solve it,  can you help me to solve it?

**Comment by guoqi1123** [comment]
Could you try the download again or check your network connection? I guess it is due to the large pickle files are not downloaded somehow due to connection issues.
