### ISSUE TITLE
Very low amplitude values near edges in static scenes

### ISSUE THREAD

**Issue by Veereshdammur** [NVlabs/FLAT#8]
Hi Qi, 

We are seeing very low amplitude values near edges in the static scene. We are not sure if it is expected behavior. Would it be possible to give a reason for that? Here are the details of the issue. 

Scene number: `1569449449898769`
image dimension: `424*512` (Kinect 2 dimension )
Measurement type: ideal (collected the first received signal and ignoring rest of the signal at pixel level ) 
The low amplitude region is highlighted with red color in the attached screenshot.  Typically the value ranges from `10-5` to `10-7`

![image](https://user-images.githubusercontent.com/33894917/75094265-e63f2580-5589-11ea-9ff7-d1356ee5e913.png)

**Comment by guoqi1123** [comment]
I think it is because the surfaces at those regions are close to parallel to the light rays emitted from the projector. Thus the returned intensity is very small based on the law of reflection.
