### ISSUE TITLE
how to generate the .pickle file?

### ISSUE THREAD

**Issue by Hongdou68** [NVlabs/FLAT#9]
Hi, i am very interesting about your project, but you have not gave the  trans_render.exe to generate the .pickle file of one scene?

**Comment by guoqi1123** [comment]
Thanks for your interests. As for the trans_render.exe, you can download it from the original [website](http://giga.cps.unizar.es/~ajarabo/pubs/transientSIGA14/code/).

**Comment by max2857** [comment]
Hi,  i want to ask how to convert the HDR image generated by the original project into the required .pickle file?
